openapi: 3.0.3
info:
  title: Relievely
  description: |-
    This is placeholder text

  contact:
    email: contact@example.org
  version: 0.1-a

tags:
  - name: activity
    description: Get information about available activites and interact with them
paths:
  /activity/{activityId}:
    get:
      tags:
        - activity
      summary: Get an existing activity
      description: Get an activity by Id
      operationId: getActivityById
      parameters:
        - name: activityId
          in: path
          description: ID of activity to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'

components:
  schemas:
    Activity:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Sleep